FROM golang:1.25-alpine

WORKDIR /backend

RUN apk add --no-cache git build-base

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/air-verse/air@latest

ENV PATH="/root/go/bin:${PATH}"

COPY . .

CMD ["air"]
