FROM golang:1.26-alpine

WORKDIR /backend

RUN apk add --no-cache git build-base

COPY go.mod go.sum ./
RUN go mod download

# #region agent log
RUN go version && go env GOVERSION GOTOOLCHAIN && \
    go install github.com/air-verse/air@latest && \
    air -v
# #endregion

ENV PATH="/root/go/bin:${PATH}"

COPY . .

CMD ["air"]
